-- Creating tables for Project DB
CREATE TABLE info (
	TICKER VARCHAR,
	sector VARCHAR,
	full_time_employees VARCHAR,
	long_business_summary VARCHAR,
	city VARCHAR,
	country VARCHAR,
	industry VARCHAR,
	ebitda_margins VARCHAR,
	profit_margins VARCHAR,
	gross_margins VARCHAR,
	operating_cash_flow VARCHAR,
    revenue_growth VARCHAR,
    operating_margins VARCHAR,
	ebitda VARCHAR,
	gross_profits VARCHAR,
	current_price VARCHAR,
	earnings_growth VARCHAR,
	current_ratio VARCHAR,
	return_on_assets VARCHAR,
	debt_to_equity VARCHAR,
	return_on_equity VARCHAR,
	total_cash VARCHAR,
	total_debt VARCHAR,
	total_revenue VARCHAR,
	quitck_ratio VARCHAR,
	long_name VARCHAR,
	book_value VARCHAR,
	average_volume VARCHAR,
	volume VARCHAR,
	fifty_two_week_high VARCHAR,
	regular_market_price VARCHAR,
	market_cap VARCHAR,
	PRIMARY KEY (ticker)
	
);